version: '3.9'


services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./frontend-react:/app/frontend

    depends_on:
      - backend

  backend: 
    build: 
      context: ./backend-django
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=library_management_system
      - SECRET_KEY=z**j4dt%ulrie&+wmob$i%yoursecretkey0l2wo1cs9ln7cx=vi3!n_+v)nig4

    ports:
      - '8000:8000'

    volumes:
      - ./backend-django:/app/backend

    depends_on:
      - db
