# Generated by Django 5.0.4 on 2024-06-17 19:48

import utils.custom_upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_author_options_alter_author_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='authors/photos/default.jpg', upload_to=utils.custom_upload_path.CustomUploadPath('authors/photos')),
        ),
    ]
